# Generated by Django 5.1.3 on 2024-12-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sec', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unfinished', 'Unfinished'), ('finished', 'Finished')], default='unfinished')),
            ],
            options={
                'db_table': 'sets',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='exercise.exercise')),
            ],
            options={
                'db_table': 'routines',
            },
        ),
    ]
