# Generated by Django 5.1.2 on 2024-10-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='status',
            field=models.CharField(choices=[('unfinished', 'Unfinished'), ('finished', 'Finished')], default='unfinished'),
        ),
    ]
