# Generated by Django 5.1.3 on 2024-12-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_set_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
