# Generated by Django 5.1.3 on 2024-12-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_remove_routine_created_at_remove_routine_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='time',
            new_name='min',
        ),
        migrations.AddField(
            model_name='set',
            name='sec',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
