services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
      - postgres

  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    command: [
      "/bin/sh", "-c",
      "poetry run python src/manage.py migrate && 
      poetry run gunicorn --chdir src --bind 0.0.0.0:8000 core.wsgi:application"
    ]
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:6
    restart: always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  nginx:
  postgres:
  redis:
