services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - prod
      - dev

  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file:
      - prod.env
    command: ["poetry", "run", "gunicorn", "--bind", "unix:/tmp/prod.sock", "config.wsgi:application"]

  dev:
    container_name: dev
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
    env_file:
      - dev.env
    command: ["poetry", "run", "gunicorn", "--bind", "unix:/tmp/dev.sock", "config.wsgi:application"]
