services:
  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file:
      - prod.env
    ports:
      - "8001:8001"
    command: ["poetry", "run", "gunicorn", "--bind", "0:8001", "config.wsgi:application"]

  dev:
    container_name: dev
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
    env_file:
      - dev.env
    ports:
      - "8000:8000"
    command: ["poetry", "run", "gunicorn", "--bind", "0:8000", "config.wsgi:application"]
