services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /tmp:/tmp
    depends_on:
      - prod
      - dev

  dev:
    container_name: dev
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
      - DEBUG=False
    volumes:
      - /tmp:/tmp
    env_file:
      - dev.env
    command: [ "poetry", "run", "gunicorn", "--bind", "127.0.0.1:8001", "config.wsgi:application" ]

  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - DEBUG=False
    volumes:
      - /tmp:/tmp
    env_file:
      - prod.env
    command: ["poetry", "run", "gunicorn", "--bind", "127.0.0.1:8002", "config.wsgi:application"]
