# Generated by Django 5.1.4 on 2024-12-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diet",
            unique_together=set(),
        ),
    ]
