# Generated by Django 5.1.4 on 2024-12-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_alter_diet_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="type",
            field=models.CharField(
                choices=[
                    ("BREAKFAST", "아침"),
                    ("BRUNCH", "아점"),
                    ("LUNCH", "점심"),
                    ("DINNER_LITE", "점저"),
                    ("DINNER", "저녁"),
                    ("MIDNIGHT_SNACK", "야식"),
                    ("SNACK", "간식"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
