# Generated by Django 5.1.3 on 2024-12-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unlabeled', 'Unlabeled')])),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField(null=True)),
                ('daily_calorie', models.PositiveSmallIntegerField(default=2500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('service_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
