# Generated by Django 5.1.3 on 2024-12-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuserprofile',
            name='daily_calorie',
            field=models.PositiveSmallIntegerField(default=2500, null=True),
        ),
    ]
