# Generated by Django 5.1.3 on 2024-12-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_serviceuserprofile_daily_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuserprofile',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
