# Generated by Django 5.1.3 on 2024-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_serviceuserprofile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuserprofile',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
