services:
  nginx:
    container_name: ssb-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - web

  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env
    command: [ "poetry", "run", "gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application" ]

volumes:
  ssb-postgres: