version: '3.9'

services:
  postgres:
    container_name: ssb-postgres
    image: postgres:16
    restart: always
    volumes:
      - ssb-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ssb
      POSTGRES_USER: ssb
      POSTGRES_PASSWORD: ssb
    ports:
      - "1234:5432"


volumes:
  ssb-postgres:
