# Generated by Django 5.1.3 on 2024-12-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='service_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciselike',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_like', to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='exerciselike',
            name='service_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'service_user')},
        ),
        migrations.AlterUniqueTogether(
            name='exerciselike',
            unique_together={('service_user', 'exercise')},
        ),
    ]
