# Generated by Django 5.1.3 on 2024-12-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exerciselike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselike',
            old_name='user',
            new_name='service_user',
        ),
    ]
