# Generated by Django 5.1.3 on 2024-12-19 01:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_alter_exercise_service_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'service_user')},
        ),
        migrations.AlterUniqueTogether(
            name='exerciselike',
            unique_together={('service_user', 'exercise')},
        ),
        migrations.AlterModelTable(
            name='exerciselike',
            table='exercise_like',
        ),
    ]
