# Generated by Django 5.1.3 on 2024-12-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField(blank=True, default=100)),
                ('calories', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('diet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='diet.diet')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
