# Generated by Django 5.1.3 on 2024-12-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='service_user',
        ),
    ]
