# Generated by Django 5.1.3 on 2024-12-21 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        ('food', '0002_remove_food_service_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='diet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='diet.diet'),
        ),
        migrations.AddField(
            model_name='food',
            name='service_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
    ]
