# Generated by Django 5.1.4 on 2024-12-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_alter_diet_unique_together"),
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="diet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food",
                to="diet.diet",
            ),
        ),
    ]
