# Generated by Django 5.1.4 on 2024-12-29 13:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_alter_diet_unique_together"),
        ("food", "0003_alter_food_diet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="food_search__8006ed_gin"
            ),
        ),
    ]
