# Generated by Django 5.1.3 on 2024-12-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_diet_food_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=100),
        ),
    ]
