# Generated by Django 5.1.4 on 2024-12-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_food_search_vector_food_food_search__8006ed_gin"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="food",
            name="food_search__8006ed_gin",
        ),
        migrations.RemoveField(
            model_name="food",
            name="search_vector",
        ),
    ]
