# Generated by Django 5.1.4 on 2024-12-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_remove_food_food_search__8006ed_gin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="image",
        ),
    ]
