name: Python3 CI

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ssb
          POSTGRES_PASSWORD: ssb
          POSTGRES_USER: ssb
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Wait for Postgres
      run: sleep 15

    - name: Migrate Database
      working-directory: ./src
      run: |
        poetry run python manage.py migrate

    - name: Run Tests
      working-directory: ./src
      run: |
        poetry run pytest